### ISSUE TITLE
Frames are too long on my machine

### ISSUE THREAD

**Issue by simevidas** [jeremenichelli/hunt#2]
I’m seeing a bunch of long frames (on the [demo page](https://jeremenichelli.github.io/hunt/)) in Chrome DevTools (marked red):

![capture](https://cloud.githubusercontent.com/assets/716405/13208287/8ea98d08-d917-11e5-9359-230429ead410.PNG)

I'm not an expert in resolving jank issues, so my suggestions are fairly basic: experiment with throttling the "scroll" event, try to see if your code performs layout trashing.

**Comment by jeremenichelli** [comment]
Hi!

Thanks por pointing this out. You're true, those are critical frames rate and I've observed them.

If you can activate the *Screenshots* checkbox, you will notice that most of those critical frames are related to the action the developer _(in this case, myself)_ is execution in the `in` and `out` callbacks. When nothing is triggered frames barely pass the *16ms* mark.

For example, when I'm lazy loading the images a big chunk of repaint is triggered, but there's no way to avoid that since you're inserting a picture which means lots of new pixels for the browsers.

Putting that aside, it's pretty hard not to cause some decrease on frame rate if you're executing code every time scroll event is triggered.

Thanks for the comment and if any idea on how to improve this comes to your mind, please report it here :smiley:
